/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PromotionDTO,
  PromotionDTOPagedResponseRequestResponse,
  PromotionDTORequestResponse,
  RequestResponse,
} from '../models';
import {
    PromotionDTOFromJSON,
    PromotionDTOToJSON,
    PromotionDTOPagedResponseRequestResponseFromJSON,
    PromotionDTOPagedResponseRequestResponseToJSON,
    PromotionDTORequestResponseFromJSON,
    PromotionDTORequestResponseToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiPromotionAddPostRequest {
    promotionDTO?: PromotionDTO;
}

export interface ApiPromotionDeleteIdDeleteRequest {
    id: string;
}

export interface ApiPromotionGetByIdIdGetRequest {
    id: string;
}

export interface ApiPromotionGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiPromotionUpdatePutRequest {
    promotionDTO?: PromotionDTO;
}

/**
 * 
 */
export class PromotionApi extends runtime.BaseAPI {

    /**
     */
    async apiPromotionAddPostRaw(requestParameters: ApiPromotionAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Promotion/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PromotionDTOToJSON(requestParameters.promotionDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPromotionAddPost(requestParameters: ApiPromotionAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPromotionAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPromotionDeleteIdDeleteRaw(requestParameters: ApiPromotionDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiPromotionDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Promotion/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPromotionDeleteIdDelete(requestParameters: ApiPromotionDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPromotionDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPromotionGetByIdIdGetRaw(requestParameters: ApiPromotionGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromotionDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiPromotionGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Promotion/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromotionDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPromotionGetByIdIdGet(requestParameters: ApiPromotionGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromotionDTORequestResponse> {
        const response = await this.apiPromotionGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPromotionGetPageGetRaw(requestParameters: ApiPromotionGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromotionDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Promotion/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromotionDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPromotionGetPageGet(requestParameters: ApiPromotionGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromotionDTOPagedResponseRequestResponse> {
        const response = await this.apiPromotionGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPromotionUpdatePutRaw(requestParameters: ApiPromotionUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Promotion/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PromotionDTOToJSON(requestParameters.promotionDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPromotionUpdatePut(requestParameters: ApiPromotionUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPromotionUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
