/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestResponse,
  ReviewAddDTO,
  ReviewDTOPagedResponseRequestResponse,
  ReviewDTORequestResponse,
} from '../models';
import {
    RequestResponseFromJSON,
    RequestResponseToJSON,
    ReviewAddDTOFromJSON,
    ReviewAddDTOToJSON,
    ReviewDTOPagedResponseRequestResponseFromJSON,
    ReviewDTOPagedResponseRequestResponseToJSON,
    ReviewDTORequestResponseFromJSON,
    ReviewDTORequestResponseToJSON,
} from '../models';

export interface ApiReviewGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiReviewIdGetRequest {
    id: string;
}

export interface ApiReviewPostRequest {
    reviewAddDTO?: ReviewAddDTO;
}

/**
 * 
 */
export class ReviewApi extends runtime.BaseAPI {

    /**
     */
    async apiReviewGetRaw(requestParameters: ApiReviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReviewDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Review`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReviewGet(requestParameters: ApiReviewGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReviewDTOPagedResponseRequestResponse> {
        const response = await this.apiReviewGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewIdGetRaw(requestParameters: ApiReviewIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReviewDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiReviewIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Review/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReviewIdGet(requestParameters: ApiReviewIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReviewDTORequestResponse> {
        const response = await this.apiReviewIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReviewPostRaw(requestParameters: ApiReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Review`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewAddDTOToJSON(requestParameters.reviewAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReviewPost(requestParameters: ApiReviewPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiReviewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
