/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArticleDTO } from './ArticleDTO';
import {
    ArticleDTOFromJSON,
    ArticleDTOFromJSONTyped,
    ArticleDTOToJSON,
} from './ArticleDTO';

/**
 * 
 * @export
 * @interface ArticleDTOPagedResponse
 */
export interface ArticleDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ArticleDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ArticleDTO>}
     * @memberof ArticleDTOPagedResponse
     */
    data?: Array<ArticleDTO> | null;
}

/**
 * Check if a given object implements the ArticleDTOPagedResponse interface.
 */
export function instanceOfArticleDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ArticleDTOPagedResponseFromJSON(json: any): ArticleDTOPagedResponse {
    return ArticleDTOPagedResponseFromJSONTyped(json, false);
}

export function ArticleDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ArticleDTOFromJSON)),
    };
}

export function ArticleDTOPagedResponseToJSON(value?: ArticleDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ArticleDTOToJSON)),
    };
}

