/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleDTO
 */
export interface ArticleDTO {
    /**
     * 
     * @type {string}
     * @memberof ArticleDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleDTO
     */
    content?: string | null;
}

/**
 * Check if a given object implements the ArticleDTO interface.
 */
export function instanceOfArticleDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ArticleDTOFromJSON(json: any): ArticleDTO {
    return ArticleDTOFromJSONTyped(json, false);
}

export function ArticleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function ArticleDTOToJSON(value?: ArticleDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'content': value.content,
    };
}

