/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoodUpdateDTO
 */
export interface FoodUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof FoodUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FoodUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FoodUpdateDTO
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof FoodUpdateDTO
     */
    kcalPer100g?: number;
    /**
     * 
     * @type {number}
     * @memberof FoodUpdateDTO
     */
    quantity?: number;
}

/**
 * Check if a given object implements the FoodUpdateDTO interface.
 */
export function instanceOfFoodUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoodUpdateDTOFromJSON(json: any): FoodUpdateDTO {
    return FoodUpdateDTOFromJSONTyped(json, false);
}

export function FoodUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'kcalPer100g': !exists(json, 'kcalPer100g') ? undefined : json['kcalPer100g'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function FoodUpdateDTOToJSON(value?: FoodUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'kcalPer100g': value.kcalPer100g,
        'quantity': value.quantity,
    };
}

