/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoodAddDTO
 */
export interface FoodAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FoodAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodAddDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FoodAddDTO
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof FoodAddDTO
     */
    kcalPer100g?: number;
    /**
     * 
     * @type {number}
     * @memberof FoodAddDTO
     */
    quantity?: number;
    /**
     * 
     * @type {Blob}
     * @memberof FoodAddDTO
     */
    img?: Blob | null;
}

/**
 * Check if a given object implements the FoodAddDTO interface.
 */
export function instanceOfFoodAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoodAddDTOFromJSON(json: any): FoodAddDTO {
    return FoodAddDTOFromJSONTyped(json, false);
}

export function FoodAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'kcalPer100g': !exists(json, 'kcalPer100g') ? undefined : json['kcalPer100g'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'img': !exists(json, 'img') ? undefined : json['img'],
    };
}

export function FoodAddDTOToJSON(value?: FoodAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'kcalPer100g': value.kcalPer100g,
        'quantity': value.quantity,
        'img': value.img,
    };
}

