/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FoodDTO } from './FoodDTO';
import {
    FoodDTOFromJSON,
    FoodDTOFromJSONTyped,
    FoodDTOToJSON,
} from './FoodDTO';

/**
 * 
 * @export
 * @interface FoodDTOListRequestResponse
 */
export interface FoodDTOListRequestResponse {
    /**
     * 
     * @type {Array<FoodDTO>}
     * @memberof FoodDTOListRequestResponse
     */
    readonly response?: Array<FoodDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FoodDTOListRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FoodDTOListRequestResponse interface.
 */
export function instanceOfFoodDTOListRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoodDTOListRequestResponseFromJSON(json: any): FoodDTOListRequestResponse {
    return FoodDTOListRequestResponseFromJSONTyped(json, false);
}

export function FoodDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodDTOListRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(FoodDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FoodDTOListRequestResponseToJSON(value?: FoodDTOListRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

