/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FoodDTOPagedResponse } from './FoodDTOPagedResponse';
import {
    FoodDTOPagedResponseFromJSON,
    FoodDTOPagedResponseFromJSONTyped,
    FoodDTOPagedResponseToJSON,
} from './FoodDTOPagedResponse';

/**
 * 
 * @export
 * @interface FoodDTOPagedResponseRequestResponse
 */
export interface FoodDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {FoodDTOPagedResponse}
     * @memberof FoodDTOPagedResponseRequestResponse
     */
    response?: FoodDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FoodDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FoodDTOPagedResponseRequestResponse interface.
 */
export function instanceOfFoodDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoodDTOPagedResponseRequestResponseFromJSON(json: any): FoodDTOPagedResponseRequestResponse {
    return FoodDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function FoodDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FoodDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FoodDTOPagedResponseRequestResponseToJSON(value?: FoodDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FoodDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

