/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FoodDTO } from './FoodDTO';
import {
    FoodDTOFromJSON,
    FoodDTOFromJSONTyped,
    FoodDTOToJSON,
} from './FoodDTO';

/**
 * 
 * @export
 * @interface FoodDTOPagedResponse
 */
export interface FoodDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof FoodDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FoodDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FoodDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<FoodDTO>}
     * @memberof FoodDTOPagedResponse
     */
    data?: Array<FoodDTO> | null;
}

/**
 * Check if a given object implements the FoodDTOPagedResponse interface.
 */
export function instanceOfFoodDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoodDTOPagedResponseFromJSON(json: any): FoodDTOPagedResponse {
    return FoodDTOPagedResponseFromJSONTyped(json, false);
}

export function FoodDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(FoodDTOFromJSON)),
    };
}

export function FoodDTOPagedResponseToJSON(value?: FoodDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(FoodDTOToJSON)),
    };
}

