/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FoodDTO } from './FoodDTO';
import {
    FoodDTOFromJSON,
    FoodDTOFromJSONTyped,
    FoodDTOToJSON,
} from './FoodDTO';

/**
 * 
 * @export
 * @interface FoodDTORequestResponse
 */
export interface FoodDTORequestResponse {
    /**
     * 
     * @type {FoodDTO}
     * @memberof FoodDTORequestResponse
     */
    response?: FoodDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FoodDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FoodDTORequestResponse interface.
 */
export function instanceOfFoodDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoodDTORequestResponseFromJSON(json: any): FoodDTORequestResponse {
    return FoodDTORequestResponseFromJSONTyped(json, false);
}

export function FoodDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FoodDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FoodDTORequestResponseToJSON(value?: FoodDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FoodDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

