/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngredientDTO
 */
export interface IngredientDTO {
    /**
     * 
     * @type {string}
     * @memberof IngredientDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientDTO
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientDTO
     */
    isAllergen?: boolean;
}

/**
 * Check if a given object implements the IngredientDTO interface.
 */
export function instanceOfIngredientDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IngredientDTOFromJSON(json: any): IngredientDTO {
    return IngredientDTOFromJSONTyped(json, false);
}

export function IngredientDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isAllergen': !exists(json, 'isAllergen') ? undefined : json['isAllergen'],
    };
}

export function IngredientDTOToJSON(value?: IngredientDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'isAllergen': value.isAllergen,
    };
}

