/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IngredientDTO } from './IngredientDTO';
import {
    IngredientDTOFromJSON,
    IngredientDTOFromJSONTyped,
    IngredientDTOToJSON,
} from './IngredientDTO';

/**
 * 
 * @export
 * @interface IngredientDTOPagedResponse
 */
export interface IngredientDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof IngredientDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<IngredientDTO>}
     * @memberof IngredientDTOPagedResponse
     */
    data?: Array<IngredientDTO> | null;
}

/**
 * Check if a given object implements the IngredientDTOPagedResponse interface.
 */
export function instanceOfIngredientDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IngredientDTOPagedResponseFromJSON(json: any): IngredientDTOPagedResponse {
    return IngredientDTOPagedResponseFromJSONTyped(json, false);
}

export function IngredientDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(IngredientDTOFromJSON)),
    };
}

export function IngredientDTOPagedResponseToJSON(value?: IngredientDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(IngredientDTOToJSON)),
    };
}

