/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { IngredientDTOPagedResponse } from './IngredientDTOPagedResponse';
import {
    IngredientDTOPagedResponseFromJSON,
    IngredientDTOPagedResponseFromJSONTyped,
    IngredientDTOPagedResponseToJSON,
} from './IngredientDTOPagedResponse';

/**
 * 
 * @export
 * @interface IngredientDTOPagedResponseRequestResponse
 */
export interface IngredientDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {IngredientDTOPagedResponse}
     * @memberof IngredientDTOPagedResponseRequestResponse
     */
    response?: IngredientDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof IngredientDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the IngredientDTOPagedResponseRequestResponse interface.
 */
export function instanceOfIngredientDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IngredientDTOPagedResponseRequestResponseFromJSON(json: any): IngredientDTOPagedResponseRequestResponse {
    return IngredientDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function IngredientDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : IngredientDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function IngredientDTOPagedResponseRequestResponseToJSON(value?: IngredientDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': IngredientDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

