/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { IngredientDTO } from './IngredientDTO';
import {
    IngredientDTOFromJSON,
    IngredientDTOFromJSONTyped,
    IngredientDTOToJSON,
} from './IngredientDTO';

/**
 * 
 * @export
 * @interface IngredientDTORequestResponse
 */
export interface IngredientDTORequestResponse {
    /**
     * 
     * @type {IngredientDTO}
     * @memberof IngredientDTORequestResponse
     */
    response?: IngredientDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof IngredientDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the IngredientDTORequestResponse interface.
 */
export function instanceOfIngredientDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IngredientDTORequestResponseFromJSON(json: any): IngredientDTORequestResponse {
    return IngredientDTORequestResponseFromJSONTyped(json, false);
}

export function IngredientDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : IngredientDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function IngredientDTORequestResponseToJSON(value?: IngredientDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': IngredientDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

