/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentIntentResponse
 */
export interface PaymentIntentResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentIntentResponse
     */
    clientSecret?: string | null;
}

/**
 * Check if a given object implements the PaymentIntentResponse interface.
 */
export function instanceOfPaymentIntentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaymentIntentResponseFromJSON(json: any): PaymentIntentResponse {
    return PaymentIntentResponseFromJSONTyped(json, false);
}

export function PaymentIntentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentIntentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientSecret': !exists(json, 'clientSecret') ? undefined : json['clientSecret'],
    };
}

export function PaymentIntentResponseToJSON(value?: PaymentIntentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientSecret': value.clientSecret,
    };
}

