/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileDTO
 */
export interface ProfileDTO {
    /**
     * 
     * @type {string}
     * @memberof ProfileDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDTO
     */
    lastName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProfileDTO
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProfileDTO
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDTO
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the ProfileDTO interface.
 */
export function instanceOfProfileDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileDTOFromJSON(json: any): ProfileDTO {
    return ProfileDTOFromJSONTyped(json, false);
}

export function ProfileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'dateOfBirth': !exists(json, 'dateOfBirth') ? undefined : (new Date(json['dateOfBirth'])),
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function ProfileDTOToJSON(value?: ProfileDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'dateOfBirth': value.dateOfBirth === undefined ? undefined : (value.dateOfBirth.toISOString()),
        'bio': value.bio,
        'avatar': value.avatar,
        'userId': value.userId,
    };
}

