/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromotionDTO
 */
export interface PromotionDTO {
    /**
     * 
     * @type {string}
     * @memberof PromotionDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionDTO
     */
    code?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PromotionDTO
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PromotionDTO
     */
    validTo?: Date;
    /**
     * 
     * @type {number}
     * @memberof PromotionDTO
     */
    discountPercentage?: number;
}

/**
 * Check if a given object implements the PromotionDTO interface.
 */
export function instanceOfPromotionDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PromotionDTOFromJSON(json: any): PromotionDTO {
    return PromotionDTOFromJSONTyped(json, false);
}

export function PromotionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'validFrom': !exists(json, 'validFrom') ? undefined : (new Date(json['validFrom'])),
        'validTo': !exists(json, 'validTo') ? undefined : (new Date(json['validTo'])),
        'discountPercentage': !exists(json, 'discountPercentage') ? undefined : json['discountPercentage'],
    };
}

export function PromotionDTOToJSON(value?: PromotionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'validFrom': value.validFrom === undefined ? undefined : (value.validFrom.toISOString()),
        'validTo': value.validTo === undefined ? undefined : (value.validTo.toISOString()),
        'discountPercentage': value.discountPercentage,
    };
}

