/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ReviewDTOPagedResponse } from './ReviewDTOPagedResponse';
import {
    ReviewDTOPagedResponseFromJSON,
    ReviewDTOPagedResponseFromJSONTyped,
    ReviewDTOPagedResponseToJSON,
} from './ReviewDTOPagedResponse';

/**
 * 
 * @export
 * @interface ReviewDTOPagedResponseRequestResponse
 */
export interface ReviewDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ReviewDTOPagedResponse}
     * @memberof ReviewDTOPagedResponseRequestResponse
     */
    response?: ReviewDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ReviewDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ReviewDTOPagedResponseRequestResponse interface.
 */
export function instanceOfReviewDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReviewDTOPagedResponseRequestResponseFromJSON(json: any): ReviewDTOPagedResponseRequestResponse {
    return ReviewDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ReviewDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ReviewDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ReviewDTOPagedResponseRequestResponseToJSON(value?: ReviewDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ReviewDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

