/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReviewDTO } from './ReviewDTO';
import {
    ReviewDTOFromJSON,
    ReviewDTOFromJSONTyped,
    ReviewDTOToJSON,
} from './ReviewDTO';

/**
 * 
 * @export
 * @interface ReviewDTOPagedResponse
 */
export interface ReviewDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ReviewDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ReviewDTO>}
     * @memberof ReviewDTOPagedResponse
     */
    data?: Array<ReviewDTO> | null;
}

/**
 * Check if a given object implements the ReviewDTOPagedResponse interface.
 */
export function instanceOfReviewDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReviewDTOPagedResponseFromJSON(json: any): ReviewDTOPagedResponse {
    return ReviewDTOPagedResponseFromJSONTyped(json, false);
}

export function ReviewDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ReviewDTOFromJSON)),
    };
}

export function ReviewDTOPagedResponseToJSON(value?: ReviewDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ReviewDTOToJSON)),
    };
}

